# Chains to monitor, with their chain identifier, Comet/Tendermint version, and the URL of their WebSocket endpoint.
[chains.cosmoshub-4]
url = "wss://neutron-rpc.lavenderfive.com/websocket"
comet_version = "0.34"

[chains.neutron-1]
url = "wss://neutron-rpc.lavenderfive.com/websocket"
comet_version = "0.34"

[chains.osmosis-1]
url = "wss://rpc.osmosis.zone/websocket"
comet_version = "0.34"

[database]
# Path to the SQLite database file where the metrics will be stored.
path = "chainpulse.db"

[metrics]
# Whether or not to expose the metrics as a Prometheus scrape endpoint.
enabled = true

# The port to expose the metrics on, at /metrics.
port = 3000
