# Example configuration for ChainPulse
# Copy this file to chainpulse.toml and modify as needed

# Global configuration
[global]
# IBC versions supported by this instance
ibc_versions = ["v1"]  # Will become ["v1", "v2"] when IBC v2 is supported

# Chains to monitor, with their chain identifier, Comet/Tendermint version, and the URL of their WebSocket endpoint.
[chains.cosmoshub-4]
url = "wss://rpc.cosmos.network/websocket"
comet_version = "0.34"  # Tendermint v0.34
ibc_version = "v1"  # Per-chain IBC version override

[chains.neutron-1]
url = "wss://neutron-rpc.lavenderfive.com/websocket"
comet_version = "0.37"  # CometBFT v0.37
# ibc_version defaults to "v1" if not specified

[chains.osmosis-1]
url = "wss://rpc.osmosis.zone/websocket"
comet_version = "0.38"  # CometBFT v0.38 (now supported!)

# Example chain with CometBFT v0.38
[chains.noble-1]
url = "wss://noble-rpc.example.com/websocket"
comet_version = "0.38"
ibc_version = "v1"

# Example chain with authentication
# [chains.private-chain]
# url = "wss://private-rpc.example.com/websocket"
# comet_version = "0.34"
# username = "your-username"
# password = "your-password"

[database]
# Path to the SQLite database file where the metrics will be stored.
path = "chainpulse.db"

[metrics]
# Whether or not to expose the metrics as a Prometheus scrape endpoint.
enabled = true

# The port to expose the metrics on, at /metrics.
port = 3000

# Whether or not to populate metrics on startup
# by querying the database for the chains which are to be monitored.
# Populating the metrics on start can take a significant amount of time
# depending on the size of the database.
populate_on_start = false