[chains]
endpoints = [
  { name = "neutron-1", comet_version = "0.34", url = "wss://neutron-rpc.lavenderfive.com/websocket" },
  { name = "osmosis-1", comet_version = "0.34", url = "wss://rpc.osmosis.zone/websocket" },
]

[database]
path = "data.db"

[metrics]
enabled = true
port    = 3000

populate_on_start = false
